services:
  db:
    image: postgres:17
    container_name: db
    environment:
      - POSTGRES_DB=ecom
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
    ports:
      - "5434:5432"
    volumes:
        - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
